version: v1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - develop
skip_tags: true
image: Ubuntu1804
build_script:
- sh: >-
    docker build -t trigrs .

    docker save --output trigrs-docker-image.tar trigrs
artifacts:
- path: trigrs-docker-image.tar
  name: landslides-trigrs-docker
deploy:
- provider: GitHub
  release: landslides-trigrs-2.1.0-dockerimage-$(appveyor_build_version)
  auth_token:
    secure: FhY46IdeJxUIp3ZcQc3n+7qgc+eFlZNTbqkJTxKlfI0iB9GZ3kMGQq+tK3yArSc7
  repository: mrck/landslides-trigrs-docker
  artifact: trigrs-docker-image.tar
  on:
    branch: master
- provider: GitHub
  release: landslides-trigrs-2.1.0-dockerimage-$(appveyor_build_version)-alpha
  auth_token:
    secure: FhY46IdeJxUIp3ZcQc3n+7qgc+eFlZNTbqkJTxKlfI0iB9GZ3kMGQq+tK3yArSc7
  repository: mrck/landslides-trigrs-docker
  artifact: trigrs-docker-image.tar
  prerelease: true
  on:
    branch: develop
